name: parkez
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  sqlite3: ^2.4.2
  sqflite: ^2.3.3+1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  icon_badge: ^1.0.0
  provider: ^6.1.2
  firebase_storage: ^12.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_native_splash: ^1.2.0
  permission_handler: ^11.3.1
  connectivity_plus: ^2.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/card.png
    - img/Logo.png
    - img/Logo2.png
    ## sugestões
    - img/sugestoes/coreuburguer.jpg
    - img/sugestoes/pizzaria.jpg
    - img/sugestoes/sushi.jpg
    # carrosel
    - img/carrosel/carrosel1.png
    - img/carrosel/carrosel2.png
    - img/carrosel/carrosel3.png
    # historico
    - img/historico/pratique.jpg
    - img/historico/shopping.png
    - img/historico/estacionamento.jpg
    - img/historico/bk.png
    # estabelecimentos
    - img/estabelecimentos/lojabk.jpg
    - img/estabelecimentos/estacionamento.jpg
    - img/estabelecimentos/pratique.jpg
    - img/estabelecimentos/shopping.jpg
