// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlx_VoSkNTjaiLICjaihsSqPlf-5XP15A',
    appId: '1:907093459787:web:20f340fd170cf9090adece',
    messagingSenderId: '907093459787',
    projectId: 'parkez-a305c',
    authDomain: 'parkez-a305c.firebaseapp.com',
    storageBucket: 'parkez-a305c.appspot.com',
    measurementId: 'G-QTK5BYSW0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7nh_t9-l4-ElF_MYPUrfhQL9Q7Dw5Uc',
    appId: '1:907093459787:android:0ec3141117ea06210adece',
    messagingSenderId: '907093459787',
    projectId: 'parkez-a305c',
    storageBucket: 'parkez-a305c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tEXsExuoQIIK0l3PJ6CNJW8lTS-iKZ8',
    appId: '1:907093459787:ios:70ec5d1d376c43800adece',
    messagingSenderId: '907093459787',
    projectId: 'parkez-a305c',
    storageBucket: 'parkez-a305c.appspot.com',
    iosBundleId: 'com.example.parkez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgRCJz53VE4kMnAgLJshhGJRgyUv11fJg',
    appId: '1:1049707254943:ios:cdb0e13c911a9b6249beaa',
    messagingSenderId: '1049707254943',
    projectId: 'parkez-1-0',
    storageBucket: 'parkez-1-0.appspot.com',
    iosBundleId: 'com.example.parkez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJn0FIRYILkzv4nyEYOhVDPUVwmJu4iNk',
    appId: '1:1049707254943:web:e1d00db582f7f65b49beaa',
    messagingSenderId: '1049707254943',
    projectId: 'parkez-1-0',
    authDomain: 'parkez-1-0.firebaseapp.com',
    storageBucket: 'parkez-1-0.appspot.com',
    measurementId: 'G-GJX7FF8LYB',
  );
}